
DROP TABLE PARTICIPANTES;
DROP TABLE PUBLICA_EXTERNO;
DROP TABLE PUBLICA;
DROP TABLE RESPONSABLE;
DROP TABLE DEDICACION;
DROP TABLE CAPITULO;
DROP TABLE TESIS;
DROP TABLE ARTICULO_REVISTA;
DROP TABLE ARTICULO_CONGRESO;
DROP TABLE LIBRO;
DROP TABLE ORGANISMO;
DROP TABLE PROYECTO;
DROP TABLE NUMERO;
DROP TABLE EDICION;
DROP TABLE EXTERNO;
DROP TABLE INVESTIGADOR;
DROP TABLE GRUPO;
DROP TABLE REVISTA;
DROP TABLE CONGRESO;
DROP TABLE AUTOR;
DROP TABLE PUBLICACION;

CREATE TABLE PUBLICACION (
       ID_PUBLICACION INTEGER NOT NULL IDENTITY PRIMARY KEY
     , TITULO VARCHAR(100) NOT NULL
     , NUM_CITAS INTEGER
);

CREATE TABLE AUTOR (
       ID_AUTOR INTEGER NOT NULL IDENTITY PRIMARY KEY
     , NOMBRE VARCHAR(60) NOT NULL
);

CREATE TABLE CONGRESO (
       ID_CONGRESO INTEGER NOT NULL IDENTITY PRIMARY KEY
     , ID_EDICION INTEGER NOT NULL
     , NOMBRE VARCHAR(80)
     , ENTIDAD VARCHAR(100)
     , TIPO VARCHAR(60)
);

CREATE TABLE REVISTA (
       ID_REVISTA INTEGER NOT NULL IDENTITY PRIMARY KEY
     , NOMBRE VARCHAR(100) NOT NULL
     , EDITORIAL VARCHAR(80)
     , ISSN CHAR(8)
     , TIPO VARCHAR(60)
);

CREATE TABLE GRUPO (
       ID_GRUPO INTEGER NOT NULL IDENTITY PRIMARY KEY
     , NOMBRE VARCHAR(80) NOT NULL
     , LINEAS_INVESTIGACION VARCHAR(400) NOT NULL
);

CREATE TABLE INVESTIGADOR (
       ID_AUTOR INTEGER NOT NULL
     , DNI CHAR(9) NOT NULL
     , E_MAIL VARCHAR(80)
     , ID_GRUPO INTEGER
     , TIPO VARCHAR(50) NOT NULL
     , FECHA_INICIO DATE
     , LIDER_GRUPO INTEGER
     , PRIMARY KEY (ID_AUTOR)
     , CONSTRAINT FK_INVESTIGADOR_1 FOREIGN KEY (ID_AUTOR)
                  REFERENCES AUTOR (ID_AUTOR)
     , CONSTRAINT FK_INVESTIGADOR_2 FOREIGN KEY (ID_GRUPO)
                  REFERENCES GRUPO (ID_GRUPO)
);

CREATE TABLE EXTERNO (
       ID_AUTOR INTEGER NOT NULL
     , UNIVERSIDAD VARCHAR(80) NOT NULL
     , PRIMARY KEY (ID_AUTOR)
     , CONSTRAINT FK_EXTERNO_1 FOREIGN KEY (ID_AUTOR)
                  REFERENCES AUTOR (ID_AUTOR)
);

CREATE TABLE EDICION (
       ID_EDICION INTEGER NOT NULL IDENTITY PRIMARY KEY
     , ID_CONGRESO INTEGER NOT NULL
     , NOMBRE VARCHAR(80) NOT NULL
     , PAIS VARCHAR(80)
     , ISBN CHAR(10)
     , FECHA_INICIO DATE
     , FECHA_FIN DATE
     , INDICE_IMPACTO FLOAT
     , CIUDAD VARCHAR(60)
     , CONSTRAINT FK_EDICION_1 FOREIGN KEY (ID_CONGRESO)
                  REFERENCES CONGRESO (ID_CONGRESO)
);

CREATE TABLE NUMERO (
       ID_NUMERO INTEGER NOT NULL IDENTITY PRIMARY KEY
     , ID_REVISTA INTEGER NOT NULL
     , NUMERO INTEGER NOT NULL
     , VOLUMEN INTEGER
     , ANYO CHAR(10)
     , INDICE_IMPACTO FLOAT
     , CONSTRAINT FK_NUMERO_1 FOREIGN KEY (ID_REVISTA)
                  REFERENCES REVISTA (ID_REVISTA)
);

CREATE TABLE PROYECTO (
       ID_PROYECTO INT NOT NULL IDENTITY PRIMARY KEY
     , TITULO VARCHAR(80) NOT NULL
     , FECHA_INICIO DATE NOT NULL
     , FECHA_FIN DATE
     , TIPO_PROYECTO VARCHAR(60)
     , ID_GRUPO INTEGER NOT NULL
     , CONSTRAINT FK_PROYECTO_1 FOREIGN KEY (ID_GRUPO)
                  REFERENCES GRUPO (ID_GRUPO)
);

CREATE TABLE ORGANISMO (
       ID_ORGANISMO INTEGER NOT NULL IDENTITY PRIMARY KEY
     , NOMBRE VARCHAR(60) NOT NULL
     , CUANTIA FLOAT NOT NULL
     , ID_PROYECTO INT NOT NULL
     , CONSTRAINT FK_ORGANISMO_1 FOREIGN KEY (ID_PROYECTO)
                  REFERENCES PROYECTO (ID_PROYECTO)
);

CREATE TABLE LIBRO (
       ID_PUBLICACION INTEGER NOT NULL
     , EDITORIAL VARCHAR(80) NOT NULL
     , ANYO INTEGER
     , PRIMARY KEY (ID_PUBLICACION)
     , CONSTRAINT FK_LIBRO_1 FOREIGN KEY (ID_PUBLICACION)
                  REFERENCES PUBLICACION (ID_PUBLICACION)
);

CREATE TABLE ARTICULO_CONGRESO (
       ID_PUBLICACION INTEGER NOT NULL
     , PAGINA_INICIO INTEGER NOT NULL
     , PAGINA_FIN INTEGER NOT NULL
     , ID_EDICION INTEGER NOT NULL
     , PRIMARY KEY (ID_PUBLICACION)
     , CONSTRAINT FK_ARTICULO_CONGRESO_1 FOREIGN KEY (ID_PUBLICACION)
                  REFERENCES PUBLICACION (ID_PUBLICACION)
     , CONSTRAINT FK_ARTICULO_CONGRESO_2 FOREIGN KEY (ID_EDICION)
                  REFERENCES EDICION (ID_EDICION)
);

CREATE TABLE ARTICULO_REVISTA (
       ID_PUBLICACION INTEGER NOT NULL
     , ID_NUMERO INTEGER NOT NULL
     , PAGINA_INICIO INTEGER
     , PAGINA_FIN INTEGER
     , PRIMARY KEY (ID_PUBLICACION)
     , CONSTRAINT FK_ARTICULO_REVISTA_1 FOREIGN KEY (ID_PUBLICACION)
                  REFERENCES PUBLICACION (ID_PUBLICACION)
     , CONSTRAINT FK_ARTICULO_REVISTA_2 FOREIGN KEY (ID_NUMERO)
                  REFERENCES NUMERO (ID_NUMERO)
);

CREATE TABLE TESIS (
       ID_PUBLICACION INTEGER NOT NULL
     , CALIFICACION VARCHAR(20)
     , FECHA_LECTURA DATE
     , ID_DIRECTOR INTEGER NOT NULL
     , ID_CODIRECTOR INTEGER
     , PRIMARY KEY (ID_PUBLICACION)
     , CONSTRAINT FK_TESIS_1 FOREIGN KEY (ID_PUBLICACION)
                  REFERENCES PUBLICACION (ID_PUBLICACION)
     , CONSTRAINT FK_TESIS_2 FOREIGN KEY (ID_DIRECTOR)
                  REFERENCES AUTOR (ID_AUTOR)
     , CONSTRAINT FK_TESIS_3 FOREIGN KEY (ID_CODIRECTOR)
                  REFERENCES AUTOR (ID_AUTOR)
);

CREATE TABLE CAPITULO (
       ID_PUBLICACION INTEGER NOT NULL
     , TITULO_LIBRO VARCHAR(60) NOT NULL
     , EDITORIAL VARCHAR(80)
     , ANYO INTEGER
     , PRIMARY KEY (ID_PUBLICACION)
     , CONSTRAINT FK_CAPITULO_1 FOREIGN KEY (ID_PUBLICACION)
                  REFERENCES PUBLICACION (ID_PUBLICACION)
);

CREATE TABLE DEDICACION (
       ES_TIEMPO_COMPLETO INTEGER NOT NULL
     , ID_PROYECTO INT NOT NULL
     , ID_AUTOR INTEGER NOT NULL
     , PRIMARY KEY (ID_PROYECTO, ID_AUTOR)
     , CONSTRAINT FK_DEDICACION_1 FOREIGN KEY (ID_PROYECTO)
                  REFERENCES PROYECTO (ID_PROYECTO)
     , CONSTRAINT FK_DEDICACION_2 FOREIGN KEY (ID_AUTOR)
                  REFERENCES INVESTIGADOR (ID_AUTOR)
);

CREATE TABLE RESPONSABLE (
       ID_PROYECTO INT NOT NULL
     , ID_AUTOR INTEGER NOT NULL
     , PRIMARY KEY (ID_PROYECTO)
     , CONSTRAINT FK_RESPONSABLE_1 FOREIGN KEY (ID_PROYECTO)
                  REFERENCES PROYECTO (ID_PROYECTO)
     , CONSTRAINT FK_RESPONSABLE_2 FOREIGN KEY (ID_AUTOR)
                  REFERENCES INVESTIGADOR (ID_AUTOR)
);

CREATE TABLE PUBLICA (
       ID_AUTOR INTEGER NOT NULL
     , ID_PUBLICACION INTEGER NOT NULL
     , PRIMARY KEY (ID_AUTOR, ID_PUBLICACION)
     , CONSTRAINT FK_PUBLICA_1 FOREIGN KEY (ID_AUTOR)
                  REFERENCES INVESTIGADOR (ID_AUTOR)
     , CONSTRAINT FK_PUBLICA_2 FOREIGN KEY (ID_PUBLICACION)
                  REFERENCES PUBLICACION (ID_PUBLICACION)
);

CREATE TABLE PUBLICA_EXTERNO (
       ID_PUBLICACION INTEGER NOT NULL
     , ID_AUTOR INTEGER NOT NULL
     , PRIMARY KEY (ID_PUBLICACION, ID_AUTOR)
     , CONSTRAINT FK_PUBLICA_EXTERNO_1 FOREIGN KEY (ID_PUBLICACION)
                  REFERENCES PUBLICACION (ID_PUBLICACION)
     , CONSTRAINT FK_PUBLICA_EXTERNO_2 FOREIGN KEY (ID_AUTOR)
                  REFERENCES EXTERNO (ID_AUTOR)
);

CREATE TABLE PARTICIPANTES (
       ID_PARTICPANTES INTEGER NOT NULL IDENTITY PRIMARY KEY
     , NOMBRE_UNIVERSIDAD VARCHAR(50) NOT NULL
     , NUM_PARTICIPANTES INTEGER
     , ID_PROYECTO INT NOT NULL
     , CONSTRAINT FK_PARTICIPANTES_1 FOREIGN KEY (ID_PROYECTO)
                  REFERENCES PROYECTO (ID_PROYECTO)
);

