package Negocio;
// default package
// Generated 07-abr-2009 11:33:02 by Hibernate Tools 3.2.0.b9

/**
 * ArticuloRevista generated by hbm2java
 */
public class ArticuloRevista implements java.io.Serializable {

	private int idPublicacion;

	private Numero numero;

	private Publicacion publicacion;

	private Integer paginaInicio;

	private Integer paginaFin;

	public ArticuloRevista() {
	}

	public ArticuloRevista(int idPublicacion, Numero numero,
			Publicacion publicacion) {
		this.idPublicacion = idPublicacion;
		this.numero = numero;
		this.publicacion = publicacion;
	}

	public ArticuloRevista(int idPublicacion, Numero numero,
			Publicacion publicacion, Integer paginaInicio, Integer paginaFin) {
		this.idPublicacion = idPublicacion;
		this.numero = numero;
		this.publicacion = publicacion;
		this.paginaInicio = paginaInicio;
		this.paginaFin = paginaFin;
	}

	public int getIdPublicacion() {
		return this.idPublicacion;
	}

	public void setIdPublicacion(int idPublicacion) {
		this.idPublicacion = idPublicacion;
	}

	public Numero getNumero() {
		return this.numero;
	}

	public void setNumero(Numero numero) {
		this.numero = numero;
	}

	public Publicacion getPublicacion() {
		return this.publicacion;
	}

	public void setPublicacion(Publicacion publicacion) {
		this.publicacion = publicacion;
	}

	public Integer getPaginaInicio() {
		return this.paginaInicio;
	}

	public void setPaginaInicio(Integer paginaInicio) {
		this.paginaInicio = paginaInicio;
	}

	public Integer getPaginaFin() {
		return this.paginaFin;
	}

	public void setPaginaFin(Integer paginaFin) {
		this.paginaFin = paginaFin;
	}

}
