package Negocio;
// default package
// Generated 07-abr-2009 11:33:02 by Hibernate Tools 3.2.0.b9

import java.util.HashSet;
import java.util.Set;

/**
 * Autor generated by hbm2java
 */
public class Autor implements java.io.Serializable {

	private int idAutor;

	private String nombre;

	private Set externos = new HashSet(0);

	private Set tesisesForIdCodirector = new HashSet(0);

	private Set tesisesForIdDirector = new HashSet(0);

	private Set investigadors = new HashSet(0);

	public Autor() {
	}

	public Autor(String nombre) {
		//this.idAutor = idAutor;
		this.nombre = nombre;
	}

	public Autor(String nombre, Set externos,
			Set tesisesForIdCodirector, Set tesisesForIdDirector,
			Set investigadors) {
		//this.idAutor = idAutor;
		this.nombre = nombre;
		this.externos = externos;
		this.tesisesForIdCodirector = tesisesForIdCodirector;
		this.tesisesForIdDirector = tesisesForIdDirector;
		this.investigadors = investigadors;
	}

	public int getIdAutor() {
		return this.idAutor;
	}

	public void setIdAutor(int idAutor) {
		this.idAutor = idAutor;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set getExternos() {
		return this.externos;
	}

	public void setExternos(Set externos) {
		this.externos = externos;
	}

	public Set getTesisesForIdCodirector() {
		return this.tesisesForIdCodirector;
	}

	public void setTesisesForIdCodirector(Set tesisesForIdCodirector) {
		this.tesisesForIdCodirector = tesisesForIdCodirector;
	}

	public Set getTesisesForIdDirector() {
		return this.tesisesForIdDirector;
	}

	public void setTesisesForIdDirector(Set tesisesForIdDirector) {
		this.tesisesForIdDirector = tesisesForIdDirector;
	}

	public Set getInvestigadors() {
		return this.investigadors;
	}

	public void setInvestigadors(Set investigadors) {
		this.investigadors = investigadors;
	}

}
