package Negocio;
// default package
// Generated 07-abr-2009 11:33:02 by Hibernate Tools 3.2.0.b9

import java.util.HashSet;
import java.util.Set;

/**
 * Congreso generated by hbm2java
 */
public class Congreso implements java.io.Serializable {

	private int idCongreso;

	private int idEdicion;

	private String nombre;

	private String entidad;

	private String tipo;

	private Set edicions = new HashSet(0);

	public Congreso() {
	}

	public Congreso(int idCongreso, int idEdicion) {
		this.idCongreso = idCongreso;
		this.idEdicion = idEdicion;
	}

	public Congreso(int idCongreso, int idEdicion, String nombre,
			String entidad, String tipo, Set edicions) {
		this.idCongreso = idCongreso;
		this.idEdicion = idEdicion;
		this.nombre = nombre;
		this.entidad = entidad;
		this.tipo = tipo;
		this.edicions = edicions;
	}

	public int getIdCongreso() {
		return this.idCongreso;
	}

	public void setIdCongreso(int idCongreso) {
		this.idCongreso = idCongreso;
	}

	public int getIdEdicion() {
		return this.idEdicion;
	}

	public void setIdEdicion(int idEdicion) {
		this.idEdicion = idEdicion;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getEntidad() {
		return this.entidad;
	}

	public void setEntidad(String entidad) {
		this.entidad = entidad;
	}

	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	public Set getEdicions() {
		return this.edicions;
	}

	public void setEdicions(Set edicions) {
		this.edicions = edicions;
	}

}
