package Negocio;
// default package
// Generated 07-abr-2009 11:33:02 by Hibernate Tools 3.2.0.b9

/**
 * DedicacionId generated by hbm2java
 */
public class DedicacionId implements java.io.Serializable {

	private int idProyecto;

	private int idAutor;

	public DedicacionId() {
	}

	public DedicacionId(int idProyecto, int idAutor) {
		this.idProyecto = idProyecto;
		this.idAutor = idAutor;
	}

	public int getIdProyecto() {
		return this.idProyecto;
	}

	public void setIdProyecto(int idProyecto) {
		this.idProyecto = idProyecto;
	}

	public int getIdAutor() {
		return this.idAutor;
	}

	public void setIdAutor(int idAutor) {
		this.idAutor = idAutor;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DedicacionId))
			return false;
		DedicacionId castOther = (DedicacionId) other;

		return (this.getIdProyecto() == castOther.getIdProyecto())
				&& (this.getIdAutor() == castOther.getIdAutor());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdProyecto();
		result = 37 * result + this.getIdAutor();
		return result;
	}

}
