package Negocio;
// default package
// Generated 07-abr-2009 11:33:02 by Hibernate Tools 3.2.0.b9

/**
 * Dedicacion generated by hbm2java
 */
public class Dedicacion implements java.io.Serializable {

	private DedicacionId id;

	private Proyecto proyecto;

	private Investigador investigador;

	private int esTiempoCompleto;

	public Dedicacion() {
	}

	public Dedicacion(DedicacionId id, Proyecto proyecto,
			Investigador investigador, int esTiempoCompleto) {
		this.id = id;
		this.proyecto = proyecto;
		this.investigador = investigador;
		this.esTiempoCompleto = esTiempoCompleto;
	}

	public DedicacionId getId() {
		return this.id;
	}

	public void setId(DedicacionId id) {
		this.id = id;
	}

	public Proyecto getProyecto() {
		return this.proyecto;
	}

	public void setProyecto(Proyecto proyecto) {
		this.proyecto = proyecto;
	}

	public Investigador getInvestigador() {
		return this.investigador;
	}

	public void setInvestigador(Investigador investigador) {
		this.investigador = investigador;
	}

	public int getEsTiempoCompleto() {
		return this.esTiempoCompleto;
	}

	public void setEsTiempoCompleto(int esTiempoCompleto) {
		this.esTiempoCompleto = esTiempoCompleto;
	}

}
