package Negocio;
// default package
// Generated 07-abr-2009 11:33:02 by Hibernate Tools 3.2.0.b9

/**
 * Organismo generated by hbm2java
 */
public class Organismo implements java.io.Serializable {

	private int idOrganismo;

	private Proyecto proyecto;

	private String nombre;

	private double cuantia;

	public Organismo() {
	}

	public Organismo(int idOrganismo, Proyecto proyecto, String nombre,
			double cuantia) {
		this.idOrganismo = idOrganismo;
		this.proyecto = proyecto;
		this.nombre = nombre;
		this.cuantia = cuantia;
	}

	public int getIdOrganismo() {
		return this.idOrganismo;
	}

	public void setIdOrganismo(int idOrganismo) {
		this.idOrganismo = idOrganismo;
	}

	public Proyecto getProyecto() {
		return this.proyecto;
	}

	public void setProyecto(Proyecto proyecto) {
		this.proyecto = proyecto;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public double getCuantia() {
		return this.cuantia;
	}

	public void setCuantia(double cuantia) {
		this.cuantia = cuantia;
	}

}
