package Negocio;
// default package
// Generated 07-abr-2009 11:33:02 by Hibernate Tools 3.2.0.b9

/**
 * Participantes generated by hbm2java
 */
public class Participantes implements java.io.Serializable {

	private int idParticpantes;

	private Proyecto proyecto;

	private String nombreUniversidad;

	private Integer numParticipantes;

	public Participantes() {
	}

	public Participantes(int idParticpantes, Proyecto proyecto,
			String nombreUniversidad) {
		this.idParticpantes = idParticpantes;
		this.proyecto = proyecto;
		this.nombreUniversidad = nombreUniversidad;
	}

	public Participantes(int idParticpantes, Proyecto proyecto,
			String nombreUniversidad, Integer numParticipantes) {
		this.idParticpantes = idParticpantes;
		this.proyecto = proyecto;
		this.nombreUniversidad = nombreUniversidad;
		this.numParticipantes = numParticipantes;
	}

	public int getIdParticpantes() {
		return this.idParticpantes;
	}

	public void setIdParticpantes(int idParticpantes) {
		this.idParticpantes = idParticpantes;
	}

	public Proyecto getProyecto() {
		return this.proyecto;
	}

	public void setProyecto(Proyecto proyecto) {
		this.proyecto = proyecto;
	}

	public String getNombreUniversidad() {
		return this.nombreUniversidad;
	}

	public void setNombreUniversidad(String nombreUniversidad) {
		this.nombreUniversidad = nombreUniversidad;
	}

	public Integer getNumParticipantes() {
		return this.numParticipantes;
	}

	public void setNumParticipantes(Integer numParticipantes) {
		this.numParticipantes = numParticipantes;
	}

}
