package Negocio;
// default package
// Generated 07-abr-2009 11:33:02 by Hibernate Tools 3.2.0.b9

import java.util.Date;

/**
 * Tesis generated by hbm2java
 */
public class Tesis implements java.io.Serializable {

	private int idPublicacion;

	private Autor autorByIdCodirector;

	private Autor autorByIdDirector;

	private Publicacion publicacion;

	private String calificacion;

	private Date fechaLectura;

	public Tesis() {
	}

	public Tesis(int idPublicacion, Autor autorByIdDirector,
			Publicacion publicacion) {
		this.idPublicacion = idPublicacion;
		this.autorByIdDirector = autorByIdDirector;
		this.publicacion = publicacion;
	}

	public Tesis(int idPublicacion, Autor autorByIdCodirector,
			Autor autorByIdDirector, Publicacion publicacion,
			String calificacion, Date fechaLectura) {
		this.idPublicacion = idPublicacion;
		this.autorByIdCodirector = autorByIdCodirector;
		this.autorByIdDirector = autorByIdDirector;
		this.publicacion = publicacion;
		this.calificacion = calificacion;
		this.fechaLectura = fechaLectura;
	}

	public int getIdPublicacion() {
		return this.idPublicacion;
	}

	public void setIdPublicacion(int idPublicacion) {
		this.idPublicacion = idPublicacion;
	}

	public Autor getAutorByIdCodirector() {
		return this.autorByIdCodirector;
	}

	public void setAutorByIdCodirector(Autor autorByIdCodirector) {
		this.autorByIdCodirector = autorByIdCodirector;
	}

	public Autor getAutorByIdDirector() {
		return this.autorByIdDirector;
	}

	public void setAutorByIdDirector(Autor autorByIdDirector) {
		this.autorByIdDirector = autorByIdDirector;
	}

	public Publicacion getPublicacion() {
		return this.publicacion;
	}

	public void setPublicacion(Publicacion publicacion) {
		this.publicacion = publicacion;
	}

	public String getCalificacion() {
		return this.calificacion;
	}

	public void setCalificacion(String calificacion) {
		this.calificacion = calificacion;
	}

	public Date getFechaLectura() {
		return this.fechaLectura;
	}

	public void setFechaLectura(Date fechaLectura) {
		this.fechaLectura = fechaLectura;
	}

}
