package Negocio;
// default package
// Generated 07-abr-2009 11:33:02 by Hibernate Tools 3.2.0.b9

/**
 * ArticuloCongreso generated by hbm2java
 */
public class ArticuloCongreso implements java.io.Serializable {

	private int idPublicacion;

	private Edicion edicion;

	private Publicacion publicacion;

	private int paginaInicio;

	private int paginaFin;

	public ArticuloCongreso() {
	}

	public ArticuloCongreso(int idPublicacion, Edicion edicion,
			Publicacion publicacion, int paginaInicio, int paginaFin) {
		this.idPublicacion = idPublicacion;
		this.edicion = edicion;
		this.publicacion = publicacion;
		this.paginaInicio = paginaInicio;
		this.paginaFin = paginaFin;
	}

	public int getIdPublicacion() {
		return this.idPublicacion;
	}

	public void setIdPublicacion(int idPublicacion) {
		this.idPublicacion = idPublicacion;
	}

	public Edicion getEdicion() {
		return this.edicion;
	}

	public void setEdicion(Edicion edicion) {
		this.edicion = edicion;
	}

	public Publicacion getPublicacion() {
		return this.publicacion;
	}

	public void setPublicacion(Publicacion publicacion) {
		this.publicacion = publicacion;
	}

	public int getPaginaInicio() {
		return this.paginaInicio;
	}

	public void setPaginaInicio(int paginaInicio) {
		this.paginaInicio = paginaInicio;
	}

	public int getPaginaFin() {
		return this.paginaFin;
	}

	public void setPaginaFin(int paginaFin) {
		this.paginaFin = paginaFin;
	}

}
