package Negocio;
// default package
// Generated 07-abr-2009 11:33:02 by Hibernate Tools 3.2.0.b9

/**
 * Capitulo generated by hbm2java
 */
public class Capitulo implements java.io.Serializable {

	private int idPublicacion;

	private Publicacion publicacion;

	private String tituloLibro;

	private String editorial;

	private Integer anyo;

	public Capitulo() {
	}

	public Capitulo(int idPublicacion, Publicacion publicacion,
			String tituloLibro) {
		this.idPublicacion = idPublicacion;
		this.publicacion = publicacion;
		this.tituloLibro = tituloLibro;
	}

	public Capitulo(int idPublicacion, Publicacion publicacion,
			String tituloLibro, String editorial, Integer anyo) {
		this.idPublicacion = idPublicacion;
		this.publicacion = publicacion;
		this.tituloLibro = tituloLibro;
		this.editorial = editorial;
		this.anyo = anyo;
	}

	public int getIdPublicacion() {
		return this.idPublicacion;
	}

	public void setIdPublicacion(int idPublicacion) {
		this.idPublicacion = idPublicacion;
	}

	public Publicacion getPublicacion() {
		return this.publicacion;
	}

	public void setPublicacion(Publicacion publicacion) {
		this.publicacion = publicacion;
	}

	public String getTituloLibro() {
		return this.tituloLibro;
	}

	public void setTituloLibro(String tituloLibro) {
		this.tituloLibro = tituloLibro;
	}

	public String getEditorial() {
		return this.editorial;
	}

	public void setEditorial(String editorial) {
		this.editorial = editorial;
	}

	public Integer getAnyo() {
		return this.anyo;
	}

	public void setAnyo(Integer anyo) {
		this.anyo = anyo;
	}

}
