package Negocio;
// default package
// Generated 07-abr-2009 11:33:02 by Hibernate Tools 3.2.0.b9

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Edicion generated by hbm2java
 */
public class Edicion implements java.io.Serializable {

	private int idEdicion;

	private Congreso congreso;

	private String nombre;

	private String pais;

	private String isbn;

	private Date fechaInicio;

	private Date fechaFin;

	private Double indiceImpacto;

	private String ciudad;

	private Set articuloCongresos = new HashSet(0);

	public Edicion() {
	}

	public Edicion(int idEdicion, Congreso congreso, String nombre) {
		this.idEdicion = idEdicion;
		this.congreso = congreso;
		this.nombre = nombre;
	}

	public Edicion(int idEdicion, Congreso congreso, String nombre,
			String pais, String isbn, Date fechaInicio, Date fechaFin,
			Double indiceImpacto, String ciudad, Set articuloCongresos) {
		this.idEdicion = idEdicion;
		this.congreso = congreso;
		this.nombre = nombre;
		this.pais = pais;
		this.isbn = isbn;
		this.fechaInicio = fechaInicio;
		this.fechaFin = fechaFin;
		this.indiceImpacto = indiceImpacto;
		this.ciudad = ciudad;
		this.articuloCongresos = articuloCongresos;
	}

	public int getIdEdicion() {
		return this.idEdicion;
	}

	public void setIdEdicion(int idEdicion) {
		this.idEdicion = idEdicion;
	}

	public Congreso getCongreso() {
		return this.congreso;
	}

	public void setCongreso(Congreso congreso) {
		this.congreso = congreso;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getPais() {
		return this.pais;
	}

	public void setPais(String pais) {
		this.pais = pais;
	}

	public String getIsbn() {
		return this.isbn;
	}

	public void setIsbn(String isbn) {
		this.isbn = isbn;
	}

	public Date getFechaInicio() {
		return this.fechaInicio;
	}

	public void setFechaInicio(Date fechaInicio) {
		this.fechaInicio = fechaInicio;
	}

	public Date getFechaFin() {
		return this.fechaFin;
	}

	public void setFechaFin(Date fechaFin) {
		this.fechaFin = fechaFin;
	}

	public Double getIndiceImpacto() {
		return this.indiceImpacto;
	}

	public void setIndiceImpacto(Double indiceImpacto) {
		this.indiceImpacto = indiceImpacto;
	}

	public String getCiudad() {
		return this.ciudad;
	}

	public void setCiudad(String ciudad) {
		this.ciudad = ciudad;
	}

	public Set getArticuloCongresos() {
		return this.articuloCongresos;
	}

	public void setArticuloCongresos(Set articuloCongresos) {
		this.articuloCongresos = articuloCongresos;
	}

}
