package Negocio;
// default package
// Generated 07-abr-2009 11:33:02 by Hibernate Tools 3.2.0.b9

import java.util.HashSet;
import java.util.Set;

/**
 * Externo generated by hbm2java
 */
public class Externo implements java.io.Serializable {

	private int idAutor;

	private Autor autor;

	private String universidad;

	private Set publicacions = new HashSet(0);

	public Externo() {
	}

	public Externo(int idAutor, Autor autor, String universidad) {
		this.idAutor = idAutor;
		this.autor = autor;
		this.universidad = universidad;
	}

	public Externo(int idAutor, Autor autor, String universidad,
			Set publicacions) {
		this.idAutor = idAutor;
		this.autor = autor;
		this.universidad = universidad;
		this.publicacions = publicacions;
	}

	public int getIdAutor() {
		return this.idAutor;
	}

	public void setIdAutor(int idAutor) {
		this.idAutor = idAutor;
	}

	public Autor getAutor() {
		return this.autor;
	}

	public void setAutor(Autor autor) {
		this.autor = autor;
	}

	public String getUniversidad() {
		return this.universidad;
	}

	public void setUniversidad(String universidad) {
		this.universidad = universidad;
	}

	public Set getPublicacions() {
		return this.publicacions;
	}

	public void setPublicacions(Set publicacions) {
		this.publicacions = publicacions;
	}

}
