package Negocio;
// default package
// Generated 07-abr-2009 11:33:02 by Hibernate Tools 3.2.0.b9

import java.util.HashSet;
import java.util.Set;

/**
 * Grupo generated by hbm2java
 */
public class Grupo implements java.io.Serializable {

	private int idGrupo;

	private String nombre;

	private String lineasInvestigacion;

	private Set proyectos = new HashSet(0);

	private Set investigadors = new HashSet(0);

	public Grupo() {
	}

	public Grupo(int idGrupo, String nombre, String lineasInvestigacion) {
		this.idGrupo = idGrupo;
		this.nombre = nombre;
		this.lineasInvestigacion = lineasInvestigacion;
	}

	public Grupo(int idGrupo, String nombre, String lineasInvestigacion,
			Set proyectos, Set investigadors) {
		this.idGrupo = idGrupo;
		this.nombre = nombre;
		this.lineasInvestigacion = lineasInvestigacion;
		this.proyectos = proyectos;
		this.investigadors = investigadors;
	}

	public int getIdGrupo() {
		return this.idGrupo;
	}

	public void setIdGrupo(int idGrupo) {
		this.idGrupo = idGrupo;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getLineasInvestigacion() {
		return this.lineasInvestigacion;
	}

	public void setLineasInvestigacion(String lineasInvestigacion) {
		this.lineasInvestigacion = lineasInvestigacion;
	}

	public Set getProyectos() {
		return this.proyectos;
	}

	public void setProyectos(Set proyectos) {
		this.proyectos = proyectos;
	}

	public Set getInvestigadors() {
		return this.investigadors;
	}

	public void setInvestigadors(Set investigadors) {
		this.investigadors = investigadors;
	}

}
