package Negocio;
// default package
// Generated 07-abr-2009 11:33:02 by Hibernate Tools 3.2.0.b9

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Investigador generated by hbm2java
 */
public class Investigador implements java.io.Serializable {

	private int idAutor;

	private Grupo grupo;

	private Autor autor;

	private String dni;

	private String EMail;

	private String tipo;

	private Date fechaInicio;

	private Integer liderGrupo;

	private Set proyectos = new HashSet(0);

	private Set publicacions = new HashSet(0);

	private Set dedicacions = new HashSet(0);

	public Investigador() {
	}

	public Investigador(int idAutor, Autor autor, String dni, String tipo) {
		this.idAutor = idAutor;
		this.autor = autor;
		this.dni = dni;
		this.tipo = tipo;
	}

	public Investigador(int idAutor, Grupo grupo, Autor autor, String dni,
			String EMail, String tipo, Date fechaInicio, Integer liderGrupo,
			Set proyectos, Set publicacions, Set dedicacions) {
		this.idAutor = idAutor;
		this.grupo = grupo;
		this.autor = autor;
		this.dni = dni;
		this.EMail = EMail;
		this.tipo = tipo;
		this.fechaInicio = fechaInicio;
		this.liderGrupo = liderGrupo;
		this.proyectos = proyectos;
		this.publicacions = publicacions;
		this.dedicacions = dedicacions;
	}

	public int getIdAutor() {
		return this.idAutor;
	}

	public void setIdAutor(int idAutor) {
		this.idAutor = idAutor;
	}

	public Grupo getGrupo() {
		return this.grupo;
	}

	public void setGrupo(Grupo grupo) {
		this.grupo = grupo;
	}

	public Autor getAutor() {
		return this.autor;
	}

	public void setAutor(Autor autor) {
		this.autor = autor;
	}

	public String getDni() {
		return this.dni;
	}

	public void setDni(String dni) {
		this.dni = dni;
	}

	public String getEMail() {
		return this.EMail;
	}

	public void setEMail(String EMail) {
		this.EMail = EMail;
	}

	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	public Date getFechaInicio() {
		return this.fechaInicio;
	}

	public void setFechaInicio(Date fechaInicio) {
		this.fechaInicio = fechaInicio;
	}

	public Integer getLiderGrupo() {
		return this.liderGrupo;
	}

	public void setLiderGrupo(Integer liderGrupo) {
		this.liderGrupo = liderGrupo;
	}

	public Set getProyectos() {
		return this.proyectos;
	}

	public void setProyectos(Set proyectos) {
		this.proyectos = proyectos;
	}

	public Set getPublicacions() {
		return this.publicacions;
	}

	public void setPublicacions(Set publicacions) {
		this.publicacions = publicacions;
	}

	public Set getDedicacions() {
		return this.dedicacions;
	}

	public void setDedicacions(Set dedicacions) {
		this.dedicacions = dedicacions;
	}

}
