package Negocio;
// default package
// Generated 07-abr-2009 11:33:02 by Hibernate Tools 3.2.0.b9

/**
 * Libro generated by hbm2java
 */
public class Libro implements java.io.Serializable {

	private int idPublicacion;

	private Publicacion publicacion;

	private String editorial;

	private Integer anyo;

	public Libro() {
	}

	public Libro(int idPublicacion, Publicacion publicacion, String editorial) {
		this.idPublicacion = idPublicacion;
		this.publicacion = publicacion;
		this.editorial = editorial;
	}

	public Libro(int idPublicacion, Publicacion publicacion, String editorial,
			Integer anyo) {
		this.idPublicacion = idPublicacion;
		this.publicacion = publicacion;
		this.editorial = editorial;
		this.anyo = anyo;
	}

	public int getIdPublicacion() {
		return this.idPublicacion;
	}

	public void setIdPublicacion(int idPublicacion) {
		this.idPublicacion = idPublicacion;
	}

	public Publicacion getPublicacion() {
		return this.publicacion;
	}

	public void setPublicacion(Publicacion publicacion) {
		this.publicacion = publicacion;
	}

	public String getEditorial() {
		return this.editorial;
	}

	public void setEditorial(String editorial) {
		this.editorial = editorial;
	}

	public Integer getAnyo() {
		return this.anyo;
	}

	public void setAnyo(Integer anyo) {
		this.anyo = anyo;
	}

}
