package Negocio;
// default package
// Generated 07-abr-2009 11:33:02 by Hibernate Tools 3.2.0.b9

import java.util.HashSet;
import java.util.Set;

/**
 * Numero generated by hbm2java
 */
public class Numero implements java.io.Serializable {

	private int idNumero;

	private Revista revista;

	private int numero;

	private Integer volumen;

	private String anyo;

	private Double indiceImpacto;

	private Set articuloRevistas = new HashSet(0);

	public Numero() {
	}

	public Numero(int idNumero, Revista revista, int numero) {
		this.idNumero = idNumero;
		this.revista = revista;
		this.numero = numero;
	}

	public Numero(int idNumero, Revista revista, int numero, Integer volumen,
			String anyo, Double indiceImpacto, Set articuloRevistas) {
		this.idNumero = idNumero;
		this.revista = revista;
		this.numero = numero;
		this.volumen = volumen;
		this.anyo = anyo;
		this.indiceImpacto = indiceImpacto;
		this.articuloRevistas = articuloRevistas;
	}

	public int getIdNumero() {
		return this.idNumero;
	}

	public void setIdNumero(int idNumero) {
		this.idNumero = idNumero;
	}

	public Revista getRevista() {
		return this.revista;
	}

	public void setRevista(Revista revista) {
		this.revista = revista;
	}

	public int getNumero() {
		return this.numero;
	}

	public void setNumero(int numero) {
		this.numero = numero;
	}

	public Integer getVolumen() {
		return this.volumen;
	}

	public void setVolumen(Integer volumen) {
		this.volumen = volumen;
	}

	public String getAnyo() {
		return this.anyo;
	}

	public void setAnyo(String anyo) {
		this.anyo = anyo;
	}

	public Double getIndiceImpacto() {
		return this.indiceImpacto;
	}

	public void setIndiceImpacto(Double indiceImpacto) {
		this.indiceImpacto = indiceImpacto;
	}

	public Set getArticuloRevistas() {
		return this.articuloRevistas;
	}

	public void setArticuloRevistas(Set articuloRevistas) {
		this.articuloRevistas = articuloRevistas;
	}

}
