package Negocio;
// default package
// Generated 07-abr-2009 11:33:02 by Hibernate Tools 3.2.0.b9

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Proyecto generated by hbm2java
 */
public class Proyecto implements java.io.Serializable {

	private int idProyecto;

	private Grupo grupo;

	private String titulo;

	private Date fechaInicio;

	private Date fechaFin;

	private String tipoProyecto;

	private Set investigadors = new HashSet(0);

	private Set participanteses = new HashSet(0);

	private Set organismos = new HashSet(0);

	private Set dedicacions = new HashSet(0);

	public Proyecto() {
	}

	public Proyecto(int idProyecto, Grupo grupo, String titulo, Date fechaInicio) {
		this.idProyecto = idProyecto;
		this.grupo = grupo;
		this.titulo = titulo;
		this.fechaInicio = fechaInicio;
	}

	public Proyecto(int idProyecto, Grupo grupo, String titulo,
			Date fechaInicio, Date fechaFin, String tipoProyecto,
			Set investigadors, Set participanteses, Set organismos,
			Set dedicacions) {
		this.idProyecto = idProyecto;
		this.grupo = grupo;
		this.titulo = titulo;
		this.fechaInicio = fechaInicio;
		this.fechaFin = fechaFin;
		this.tipoProyecto = tipoProyecto;
		this.investigadors = investigadors;
		this.participanteses = participanteses;
		this.organismos = organismos;
		this.dedicacions = dedicacions;
	}

	public int getIdProyecto() {
		return this.idProyecto;
	}

	public void setIdProyecto(int idProyecto) {
		this.idProyecto = idProyecto;
	}

	public Grupo getGrupo() {
		return this.grupo;
	}

	public void setGrupo(Grupo grupo) {
		this.grupo = grupo;
	}

	public String getTitulo() {
		return this.titulo;
	}

	public void setTitulo(String titulo) {
		this.titulo = titulo;
	}

	public Date getFechaInicio() {
		return this.fechaInicio;
	}

	public void setFechaInicio(Date fechaInicio) {
		this.fechaInicio = fechaInicio;
	}

	public Date getFechaFin() {
		return this.fechaFin;
	}

	public void setFechaFin(Date fechaFin) {
		this.fechaFin = fechaFin;
	}

	public String getTipoProyecto() {
		return this.tipoProyecto;
	}

	public void setTipoProyecto(String tipoProyecto) {
		this.tipoProyecto = tipoProyecto;
	}

	public Set getInvestigadors() {
		return this.investigadors;
	}

	public void setInvestigadors(Set investigadors) {
		this.investigadors = investigadors;
	}

	public Set getParticipanteses() {
		return this.participanteses;
	}

	public void setParticipanteses(Set participanteses) {
		this.participanteses = participanteses;
	}

	public Set getOrganismos() {
		return this.organismos;
	}

	public void setOrganismos(Set organismos) {
		this.organismos = organismos;
	}

	public Set getDedicacions() {
		return this.dedicacions;
	}

	public void setDedicacions(Set dedicacions) {
		this.dedicacions = dedicacions;
	}

}
