package Negocio;
// default package
// Generated 07-abr-2009 11:33:02 by Hibernate Tools 3.2.0.b9

import java.util.HashSet;
import java.util.Set;

/**
 * Publicacion generated by hbm2java
 */
public class Publicacion implements java.io.Serializable {

	private int idPublicacion;

	private String titulo;

	private Integer numCitas;

	private Set externos = new HashSet(0);

	private Set articuloCongresos = new HashSet(0);

	private Set capitulos = new HashSet(0);

	private Set investigadors = new HashSet(0);

	private Set libros = new HashSet(0);

	private Set tesises = new HashSet(0);

	private Set articuloRevistas = new HashSet(0);

	public Publicacion() {
	}

	public Publicacion(int idPublicacion, String titulo) {
		this.idPublicacion = idPublicacion;
		this.titulo = titulo;
	}

	public Publicacion(int idPublicacion, String titulo, Integer numCitas,
			Set externos, Set articuloCongresos, Set capitulos,
			Set investigadors, Set libros, Set tesises, Set articuloRevistas) {
		this.idPublicacion = idPublicacion;
		this.titulo = titulo;
		this.numCitas = numCitas;
		this.externos = externos;
		this.articuloCongresos = articuloCongresos;
		this.capitulos = capitulos;
		this.investigadors = investigadors;
		this.libros = libros;
		this.tesises = tesises;
		this.articuloRevistas = articuloRevistas;
	}

	public int getIdPublicacion() {
		return this.idPublicacion;
	}

	public void setIdPublicacion(int idPublicacion) {
		this.idPublicacion = idPublicacion;
	}

	public String getTitulo() {
		return this.titulo;
	}

	public void setTitulo(String titulo) {
		this.titulo = titulo;
	}

	public Integer getNumCitas() {
		return this.numCitas;
	}

	public void setNumCitas(Integer numCitas) {
		this.numCitas = numCitas;
	}

	public Set getExternos() {
		return this.externos;
	}

	public void setExternos(Set externos) {
		this.externos = externos;
	}

	public Set getArticuloCongresos() {
		return this.articuloCongresos;
	}

	public void setArticuloCongresos(Set articuloCongresos) {
		this.articuloCongresos = articuloCongresos;
	}

	public Set getCapitulos() {
		return this.capitulos;
	}

	public void setCapitulos(Set capitulos) {
		this.capitulos = capitulos;
	}

	public Set getInvestigadors() {
		return this.investigadors;
	}

	public void setInvestigadors(Set investigadors) {
		this.investigadors = investigadors;
	}

	public Set getLibros() {
		return this.libros;
	}

	public void setLibros(Set libros) {
		this.libros = libros;
	}

	public Set getTesises() {
		return this.tesises;
	}

	public void setTesises(Set tesises) {
		this.tesises = tesises;
	}

	public Set getArticuloRevistas() {
		return this.articuloRevistas;
	}

	public void setArticuloRevistas(Set articuloRevistas) {
		this.articuloRevistas = articuloRevistas;
	}

}
