package Negocio;
// default package
// Generated 07-abr-2009 11:33:02 by Hibernate Tools 3.2.0.b9

import java.util.HashSet;
import java.util.Set;

/**
 * Revista generated by hbm2java
 */
public class Revista implements java.io.Serializable {

	private int idRevista;

	private String nombre;

	private String editorial;

	private String issn;

	private String tipo;

	private Set numeros = new HashSet(0);

	public Revista() {
	}

	public Revista(int idRevista, String nombre) {
		this.idRevista = idRevista;
		this.nombre = nombre;
	}

	public Revista(int idRevista, String nombre, String editorial, String issn,
			String tipo, Set numeros) {
		this.idRevista = idRevista;
		this.nombre = nombre;
		this.editorial = editorial;
		this.issn = issn;
		this.tipo = tipo;
		this.numeros = numeros;
	}

	public int getIdRevista() {
		return this.idRevista;
	}

	public void setIdRevista(int idRevista) {
		this.idRevista = idRevista;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getEditorial() {
		return this.editorial;
	}

	public void setEditorial(String editorial) {
		this.editorial = editorial;
	}

	public String getIssn() {
		return this.issn;
	}

	public void setIssn(String issn) {
		this.issn = issn;
	}

	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	public Set getNumeros() {
		return this.numeros;
	}

	public void setNumeros(Set numeros) {
		this.numeros = numeros;
	}

}
